// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl87BFC9Sb_Qw062pzPxHQTCJIVFzu5Sw',
    appId: '1:645527805273:web:6f45040d46450193910048',
    messagingSenderId: '645527805273',
    projectId: 'bloodconnect-b0e96',
    authDomain: 'bloodconnect-b0e96.firebaseapp.com',
    storageBucket: 'bloodconnect-b0e96.firebasestorage.app',
    measurementId: 'G-BF0KDZG557',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB517D8KUVznowtGHJam3EFRJgAPTseySw',
    appId: '1:645527805273:android:437c4f7d1ec3f41d910048',
    messagingSenderId: '645527805273',
    projectId: 'bloodconnect-b0e96',
    storageBucket: 'bloodconnect-b0e96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwP9itfUJuc9YjDyjN1WjUdlHEB0G1PHU',
    appId: '1:645527805273:ios:856d53721dbab619910048',
    messagingSenderId: '645527805273',
    projectId: 'bloodconnect-b0e96',
    storageBucket: 'bloodconnect-b0e96.firebasestorage.app',
    iosBundleId: 'com.example.bloodconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwP9itfUJuc9YjDyjN1WjUdlHEB0G1PHU',
    appId: '1:645527805273:ios:856d53721dbab619910048',
    messagingSenderId: '645527805273',
    projectId: 'bloodconnect-b0e96',
    storageBucket: 'bloodconnect-b0e96.firebasestorage.app',
    iosBundleId: 'com.example.bloodconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl87BFC9Sb_Qw062pzPxHQTCJIVFzu5Sw',
    appId: '1:645527805273:web:9ea043b3fb7c844e910048',
    messagingSenderId: '645527805273',
    projectId: 'bloodconnect-b0e96',
    authDomain: 'bloodconnect-b0e96.firebaseapp.com',
    storageBucket: 'bloodconnect-b0e96.firebasestorage.app',
    measurementId: 'G-2J393821D1',
  );
}
